// <auto-generated />
using System;
using GarmentWorkshop.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarmentWorkshop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831144953_AddMachineAndMaintenance")]
    partial class AddMachineAndMaintenance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GarmentWorkshop.Models.Garment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Garments");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.MachineMaintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineMaintenances");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PiecesProduced")
                        .HasColumnType("int");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("WorkerId", "Date");

                    b.ToTable("Productions");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpectedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GarmentId")
                        .HasColumnType("int");

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<decimal>("PartyRatePerPiece")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalPieces")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GarmentId");

                    b.HasIndex("PartyId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.WorkerRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<int>("GarmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("RatePerPiece")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GarmentId");

                    b.HasIndex("WorkerId", "GarmentId", "EffectiveFrom");

                    b.ToTable("WorkerRates");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.MachineMaintenance", b =>
                {
                    b.HasOne("GarmentWorkshop.Models.Machine", "Machine")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.Production", b =>
                {
                    b.HasOne("GarmentWorkshop.Models.WorkOrder", "WorkOrder")
                        .WithMany("Productions")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GarmentWorkshop.Models.Worker", "Worker")
                        .WithMany("Productions")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkOrder");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.WorkOrder", b =>
                {
                    b.HasOne("GarmentWorkshop.Models.Garment", "Garment")
                        .WithMany("WorkOrders")
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GarmentWorkshop.Models.Party", "Party")
                        .WithMany("WorkOrders")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Garment");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.WorkerRate", b =>
                {
                    b.HasOne("GarmentWorkshop.Models.Garment", "Garment")
                        .WithMany("WorkerRates")
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GarmentWorkshop.Models.Worker", "Worker")
                        .WithMany("WorkerRates")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Garment");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.Garment", b =>
                {
                    b.Navigation("WorkOrders");

                    b.Navigation("WorkerRates");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.Machine", b =>
                {
                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.Party", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.WorkOrder", b =>
                {
                    b.Navigation("Productions");
                });

            modelBuilder.Entity("GarmentWorkshop.Models.Worker", b =>
                {
                    b.Navigation("Productions");

                    b.Navigation("WorkerRates");
                });
#pragma warning restore 612, 618
        }
    }
}
